name: Build Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          # from http://askubuntu.com/a/25614
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get install -y ttf-mscorefonts-installer biber make texlive-lang-chinese texlive-xetex

      - name: Build
        run: make slides

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: slides.pdf
